wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/3d_rollball_objects_cv.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/3d_rollball_objects_v2.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/BrokenJigsawbrokenjigsaw_swap.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/card.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/cardistance.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/conveyor.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/coordinatesmatch.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/coordinatesmatch_cv.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/counting.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/dicematch.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/dice_pair.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/frankenhead.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/hand_number_puzzle.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/hopscotch_highsec.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/knotsCrossesCircle.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/penguin.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/penguins-icon.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/penguins.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/rockstack.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/rockstack_v2.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/shadows.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/train_coordinates.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/train_coordinates_cv.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/unbentobjects.onnx
wget -P /app/funcaptcha_challenger https://funcaptchamodel.unix.do/version.json